version: "3"
services:
  nginx:
    ports:
      - "9000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
    # all files in folder will be copied to app folder of container to keep the source code in sync
      - ./:/app
    #  node_modules folder will not be synced tp /app folder as we run npm install while creating the image
      - /app/node_modules
    # enviornment:
    #   - NODE_ENV=development
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass123
      