version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "9000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    env_file:
      - ./.env
    build: .
    # ports:
    #   - "9000:9000"
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass123
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: